### ISSUE TITLE
URGENT - What is OAuthAwareObject

### ISSUE THREAD

**Issue by vishalTatvaSoft** [marketplacer/lightspeed_pos#29]
Can somebody explain me what OAuthAwareObject ?
I am getting this response when i request for access token
```
{"access_token"=>"******************************************************",
 "expires_in"=>1800,
 "token_type"=>"bearer",
 "scope"=>"employee:inventory employee:admin_shops employee:register",
 "refresh_token"=>"*********************************************************"}
```
when i try to use client = Lightspeed::Client.new(oauth_token_holder: "lightspeed_repsonse"), i am getting error 

> NoMethodError: undefined method `oauth_token' for #<Hash:0x00007f45ca4fedd8>

Am i missing something ?

**Comment by robotdana** [comment]
It should be an object, possibly an instance of a class (in our it's a rails record)) with a method `oauth_token` that returns the current token, and `refresh_oauth_token` that requests a new token and stores it, so that the next time `oauth_token` is called on this object it returns the new token.

because it needs to be in charge of requesting the new oauth token it can't be a Hash

**Comment by vishalTatvaSoft** [comment]
@robotdana   Do i need to generate this object manually ? do you have any sample code how to generate it ?
